### ISSUE TITLE
[Feature] Support MinestomPvP

### ISSUE THREAD

**Issue by mani1232** [bladehuntmc/KotStom#4]
https://github.com/TogAr2/MinestomPvP

**Comment by oglassdev** [comment]
Is there any kotlin specific features that could make the MinestomPvP experience easier? I'm not quite familiar with it

**Comment by mani1232** [comment]
Coroutines, kotlin builders, and other features

**Comment by oglassdev** [comment]
I've finally gotten around to an attempt at a dsl for this (busy w/ game jam stuff). Anyway, take a look at this. Lmk any thoughts
<img width="768" alt="Screenshot 2024-08-16 at 3 28 09 PM" src="https://github.com/user-attachments/assets/f147f7ab-ac7c-488d-bb19-991d66f809cc">

**Comment by oglassdev** [comment]
This was completed by #6
